version: '3.8'

services:
  backend-api:
    image: weather-backend
    build:
      context: ../backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"

  weather-ui:
    image: weather-frontend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - backend-api
